name: Oryon Security Scan

on:
  push:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  oryon:
    uses: Oryon-Technology/oryon-cicd-pipeline/.github/workflows/scan.yml@v1
    secrets:
      ORYON_CI_TOKEN: ${{ secrets.ORYON_CI_TOKEN }}
