name: Oryon Security Scan

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  oryon:
    uses: Guayamose/oryon-action/.github/workflows/scan.yml@v1
    with:
      fail-on: none
    secrets:
      ORYON_CI_TOKEN: ${{ secrets.ORYON_CI_TOKEN }}
